services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in elasticsearch.yml
      - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
      - "xpack.security.enabled=false" # disable https, enable http
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    networks:
      elasticsearch:
    ports:
      - target: 9200
        published: 9200
      - target: 9300
        published: 9300
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2
    depends_on:
      - elasticsearch
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]'
    networks:
      elasticsearch:
    ports:
      - target: 5601
        published: 5601
  jupyter:
    image: quay.io/jupyter/minimal-notebook
    depends_on:
      - elasticsearch
    networks:
      elasticsearch:
    command: "start-notebook.py --IdentityProvider.token=''"
    ports:
      - target: 8888
        published: 8888
    volumes:
      - source: "$PWD"
        target: /home/jovyan/work
        type: bind
volumes:
  elasticsearch:
networks:
  elasticsearch: